services:
  web:
    build: .
    environment:
      MYENV: telow_instance
    volumes:
      - .:/code
    
  web_migrate:
    extends:
      service: web
    command: python telow/manage.py migrate
    volumes:
      - ./telow/db:/src/local-db
  web_run:
    extends:
      service: web
    command: python telow/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"