# Generated by Django 3.2.4 on 2021-10-15 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20211015_1818'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='workflow_id',
        ),
        migrations.AddField(
            model_name='order',
            name='process_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.process', verbose_name='process'),
        ),
    ]
