# Generated by Django 3.2.4 on 2021-10-16 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20211015_2204'),
        ('order', '0004_alter_order_order_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_meta',
            name='status',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='main_app.status'),
        ),
    ]
