# Generated by Django 3.2.4 on 2021-10-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_meta_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_meta',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
