# Generated by Django 3.2.4 on 2021-10-31 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_department'),
        ('order', '0010_alter_order_meta_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_meta',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order_meta',
            name='process_action',
        ),
        migrations.RemoveField(
            model_name='order_meta',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order_meta',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='order_meta',
            name='meta_name',
            field=models.CharField(default='nil', max_length=155),
        ),
        migrations.AddField(
            model_name='order_meta',
            name='meta_value',
            field=models.CharField(default='nil', max_length=555),
        ),
        migrations.CreateModel(
            name='order_process_action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('process_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.process_action')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main_app.status')),
            ],
        ),
    ]
