# Generated by Django 3.2.8 on 2021-11-14 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20211110_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order_meta',
            options={'permissions': [('Can_view_litography', 'can view litography details'), ('Can_view_paper', 'can view paper details'), ('Can_view_hotstamp', 'can view hotstamp details'), ('Can_view_befor_cut', 'can view befor cut details'), ('Can_view_print', 'can view print details'), ('Can_view_hard_cover', 'can view hard cover details'), ('Can_view_plastic_cover', 'can view plastice cover details'), ('Can_view_part_cover', 'can view part cover details'), ('Can_view_shield', 'can view sheidl details'), ('Can_view_window_sticking', 'can view window sticking details'), ('Can_view_box_sticking', 'can view box sticking details'), ('Can_view_bindray', 'can view bindray details'), ('Can_view_customize', 'can view customize details'), ('Can_view_packaging', 'can view packaging details')]},
        ),
    ]
