# Generated by Django 3.2.8 on 2021-11-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_order_meta_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('DO OR DIE', 'Do or die'), ('Critical', 'Critical priority'), ('High', 'High priority'), ('Middle', 'Middle priority'), ('Low', 'Low priority')], default='Low priority', max_length=11),
        ),
    ]
