# Generated by Django 3.2.4 on 2021-10-13 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211012_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_name', models.CharField(max_length=55)),
                ('depart_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_name', models.CharField(max_length=155)),
                ('workflow_description', models.CharField(max_length=500)),
                ('isEnable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='workflow_meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.department', verbose_name='Department')),
                ('action_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_action', to='main_app.action', verbose_name='action')),
                ('previous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_action', to='main_app.action', verbose_name='dependent_action')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.status', verbose_name='status')),
                ('workflow_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.workflow', verbose_name='workflow_id')),
            ],
        ),
    ]
