# Generated by Django 3.2.4 on 2021-10-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_workflow_meta_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=155)),
                ('process_description', models.CharField(max_length=500)),
                ('isEnable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='process_action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='workflow_meta',
            name='Department',
        ),
        migrations.RemoveField(
            model_name='workflow_meta',
            name='action_id',
        ),
        migrations.RemoveField(
            model_name='workflow_meta',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='workflow_meta',
            name='previous',
        ),
        migrations.RemoveField(
            model_name='workflow_meta',
            name='status',
        ),
        migrations.RemoveField(
            model_name='workflow_meta',
            name='workflow_id',
        ),
        migrations.DeleteModel(
            name='department',
        ),
    ]
