# Generated by Django 3.2.4 on 2021-10-15 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20211015_1818'),
        ('main_app', '0008_auto_20211015_1818'),
    ]

    operations = [
        migrations.DeleteModel(
            name='workflow',
        ),
        migrations.DeleteModel(
            name='workflow_meta',
        ),
        migrations.AddField(
            model_name='process_action',
            name='action_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.action'),
        ),
        migrations.AddField(
            model_name='process_action',
            name='process_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.process'),
        ),
    ]
