# Generated by Django 3.2.4 on 2021-10-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_status_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(max_length=55, unique=True),
        ),
    ]
