# Generated by Django 3.2.4 on 2021-10-26 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_action_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_action',
            name='action_id',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='process_action',
            name='dependency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.process_action'),
        ),
    ]
