# Generated by Django 3.2.4 on 2021-10-26 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_rename_action_id_process_action_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_action',
            name='dependency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.process_action'),
        ),
    ]
