# Generated by Django 3.2.4 on 2021-10-27 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_auto_20211027_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='dependency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.action'),
        ),
        migrations.AlterField(
            model_name='process_action',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.action'),
        ),
        migrations.AlterField(
            model_name='process_action',
            name='process_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.process'),
        ),
    ]
