# Generated by Django 3.2.4 on 2021-10-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='color',
            field=models.CharField(default='e3e3e3', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_title',
            field=models.CharField(default='تعیین نشده', max_length=55),
        ),
    ]
