# Generated by Django 3.2.8 on 2021-11-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_mobile',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_phone',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
