# Generated by Django 3.2.4 on 2021-10-13 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20211013_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_meta',
            name='previous',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_action', to='main_app.action', verbose_name='dependent action'),
        ),
    ]
