# Generated by Django 3.2.4 on 2021-10-13 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('main_app', '0006_alter_workflow_meta_previous'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow_meta',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
