# Generated by Django 3.2.4 on 2021-10-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20211015_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='description',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
