# Generated by Django 3.2.4 on 2021-10-15 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_status_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_action',
            name='dependency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependent_action', to='main_app.action'),
        ),
        migrations.AlterField(
            model_name='process_action',
            name='action_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_action', to='main_app.action'),
        ),
    ]
