# Generated by Django 3.2.4 on 2021-10-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20211015_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_action',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='process_action',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
