# Generated by Django 3.2.4 on 2021-10-27 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_alter_process_action_dependency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process_action',
            name='dependency',
        ),
        migrations.AddField(
            model_name='action',
            name='dependency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.action'),
        ),
        migrations.AlterField(
            model_name='process_action',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.action'),
        ),
    ]
