# Generated by Django 3.2.4 on 2021-10-31 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_auto_20211031_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_action',
            name='process_id',
            field=models.ForeignKey(default='تعیین نشده', on_delete=django.db.models.deletion.PROTECT, to='main_app.process'),
        ),
    ]
