# Generated by Django 3.2.9 on 2021-12-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_status_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_action',
            name='priority',
            field=models.IntegerField(null=True),
        ),
    ]
