# Generated by Django 3.2.9 on 2021-12-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_process_action_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_action',
            name='priority',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
