# Generated by Django 3.2.4 on 2021-10-15 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_status_description'),
        ('order', '0002_auto_20211015_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='process_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.process'),
        ),
        migrations.CreateModel(
            name='order_meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('process_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.process_action')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.status')),
            ],
        ),
    ]
