# Generated by Django 3.2.4 on 2021-10-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20211015_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
