# Generated by Django 3.2.4 on 2021-10-27 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_auto_20211027_0833'),
        ('order', '0008_auto_20211027_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_meta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_meta',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.status'),
        ),
    ]
