# Generated by Django 3.2.4 on 2021-11-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20211031_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_meta',
            name='meta_name',
        ),
        migrations.AlterField(
            model_name='order_meta',
            name='meta_value',
            field=models.JSONField(null=True),
        ),
    ]
